version: "3.9"

services:
  postgresql:
    image: sameersbn/postgresql:9.6-2
    environment:
      - DB_USER=gitlab
      - DB_PASS=password
      - DB_NAME=gitlabhq_production
      - DB_EXTENSION=pg_trgm

  redis:
    image: sameersbn/redis:latest

  gitlab:
    depends_on:
      - postgresql
      - redis
    image: sameersbn/gitlab:9.1.0-1
    ports:
      - "10080:80"
      - "10022:22"
    environment:
      - GITLAB_PORT=10080
      - GITLAB_SSH_PORT=10022
      - GITLAB_SECRETS_DB_KEY_BASE=long-and-random-alpha-numeric-string
      - GITLAB_SECRETS_SECRET_KEY_BASE=long-and-random-alpha-numeric-string
      - GITLAB_SECRETS_OTP_KEY_BASE=long-and-random-alpha-numeric-string
    