version: "3.9"

services:
  postgresql:
    image: sameersbn/postgresql:9.6-2
    environment:
      - DB_USER=redmine
      - DB_PASS=password
      - DB_NAME=redmine_production

  redmine:
    depends_on:
      - postgresql
    image: sameersbn/redmine:3.3.2-1
    ports:
      - "10083:80"
    environment:
      - REDMINE_PORT=10083
    